services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: bsp
      POSTGRES_PASSWORD: bsp
      POSTGRES_DB: bsp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
